### ISSUE TITLE
Add a `wait` subcommand and a `--wait` option to `provision`

### ISSUE THREAD

**Issue by lexi-lambda** [cjdev/cloudseeder#22]
Currently, deploying a stack just tells AWS to apply the changeset, then exits. However, when deploying multiple stacks, it would be extremely useful to be able to wait for a stack to finish creating or updating. Ideally, this would be via a `wait` subcommand, which could be used to wait until a stack finishes changing, similar to `aws cloudformation wait`. Additionally, a `--wait` option could be provided to `provision`, which would be similar to `provision <env> <stack> && wait <env> <stack>`.

**Comment by adlaika** [comment]
closed by #30
